In [1]:
import pandas as pd 
import numpy as np
import  matplotlib.pyplot as plt
from scipy.fftpack import fft,fft2, fftshift
from mpl_toolkits.mplot3d import Axes3D

In [21]:
#read the data
fs=1200
position_data= pd.read_csv('AB_13_G1_0 - Report1.txt', sep="\t", header=None)
#position_data.describe[:,3:23]
A= position_data.iloc[:,3:6][1:].astype(float)#[6][1:].astype(float)
print(A)


               3         4         5
1      -1.376459  0.233045  0.731950
2      -1.376642  0.233027  0.731820
3      -1.376705  0.233049  0.731755
4      -1.376682  0.233104  0.731732
5      -1.376625  0.233186  0.731717
6      -1.376587  0.233286  0.731676
7      -1.376620  0.233396  0.731575
8      -1.376762  0.233511  0.731392
9      -1.376988  0.233624  0.731150
10     -1.377261  0.233731  0.730884
11     -1.377541  0.233826  0.730629
12     -1.377791  0.233906  0.730420
13     -1.377983  0.233964  0.730280
14     -1.378139  0.233991  0.730184
15     -1.378291  0.233978  0.730093
16     -1.378471  0.233914  0.729971
17     -1.378713  0.233790  0.729779
18     -1.379033  0.233602  0.729496
19     -1.379379  0.233380  0.729169
20     -1.379685  0.233159  0.728860
21     -1.379883  0.232975  0.728632
22     -1.379905  0.232863  0.728548
23     -1.379708  0.232850  0.728652
24     -1.379343  0.232914  0.728906
25     -1.378884  0.233026  0.729255
26     -1.378405  0.233155  0.729643
2

In [18]:
t=np.linspace(0 ,len(A)/fs,len(A))
T=position_data.iloc[:,2][1:].astype(float)
print(t)
print(T)

[0.00000000e+00 8.33336950e-04 1.66667390e-03 ... 1.91986667e+02
 1.91987500e+02 1.91988333e+02]
1           0.000000
2           0.000833
3           0.001667
4           0.002500
5           0.003333
6           0.004167
7           0.005000
8           0.005833
9           0.006667
10          0.007500
11          0.008333
12          0.009167
13          0.010000
14          0.010833
15          0.011667
16          0.012500
17          0.013333
18          0.014167
19          0.015000
20          0.015833
21          0.016667
22          0.017500
23          0.018333
24          0.019167
25          0.020000
26          0.020833
27          0.021667
28          0.022500
29          0.023333
30          0.024167
             ...    
230357    191.963333
230358    191.964167
230359    191.965000
230360    191.965833
230361    191.966667
230362    191.967500
230363    191.968333
230364    191.969167
230365    191.970000
230366    191.970833
230367    191.971667
230368    191.972500


In [19]:
#proportion of varience 
A_std=(A-np.mean(A, axis=0))/np.std(A, axis=0)
print(A_std)

               3         4         5
1       0.375166  0.662439  0.524872
2       0.374363  0.662203  0.524261
3       0.374087  0.662491  0.523956
4       0.374188  0.663210  0.523848
5       0.374438  0.664282  0.523777
6       0.374604  0.665589  0.523585
7       0.374460  0.667027  0.523110
8       0.373837  0.668530  0.522251
9       0.372845  0.670007  0.521114
10      0.371647  0.671406  0.519865
11      0.370419  0.672648  0.518667
12      0.369322  0.673693  0.517686
13      0.368480  0.674451  0.517028
14      0.367795  0.674804  0.516577
15      0.367128  0.674634  0.516150
16      0.366338  0.673798  0.515577
17      0.365277  0.672177  0.514675
18      0.363873  0.669719  0.513346
19      0.362355  0.666818  0.511810
20      0.361012  0.663929  0.510359
21      0.360143  0.661524  0.509288
22      0.360047  0.660060  0.508894
23      0.360911  0.659890  0.509382
24      0.362513  0.660726  0.510575
25      0.364526  0.662190  0.512214
26      0.366628  0.663877  0.514036
2

In [63]:
#covarience
#covr_matrix=np.cov(A_std, rowvar= True)
#covr_matrix1=np.cov(A_std, rowvar= False)
#print("covr_matrix1.shape> " +str(covr_matrix.shape))
#print("covr_matrix1.shape1> " +str(covr_matrix.shape))
#print("covarience of matrix is:  n\%s"  %covr_matrix1)
#covr_matrix=np.cov(A.iloc[:,0][1:].astype(float),A.iloc[:,1][1:].astype(float),A.iloc[:,2][1:].astype(float)) 
#print("Shape of array:\n", np.shape(covr_matrix)) 
  
#print("Covarinace matrix is:  n\%s"  % covr_matrix)
#print(np.cov(pd.to_neumeric(covr_matrix)))
x = A.iloc[:,0][0:].astype(float)
  
y =A.iloc[:,1][0:].astype(float)
z =A.iloc[:,2][0:].astype(float)
  
# find out covariance with respect  rows 
cov_mat = np.stack((x, y, z), axis = 1)  
print(cov_mat)
  
print("shape of matrix x ,y & z:", np.shape(cov_mat)) 
  
#print("shape of covariance matrix:", np.shape(np.cov(cov_mat))) 
matrix=np.cov(cov_mat) 
print(matrix) 


[[-1.376459  0.233045  0.73195 ]
 [-1.376642  0.233027  0.73182 ]
 [-1.376705  0.233049  0.731755]
 ...
 [-0.797966  0.055934  0.858962]
 [-0.797927  0.055922  0.859011]
 [-0.79786   0.055917  0.859085]]
shape of matrix x ,y & z: (230386, 3)


MemoryError: 

In [58]:
eigenvalues,eigenvectors=np.linalg.eig(cov_mat)

LinAlgError: Last 2 dimensions of the array must be square